### ISSUE TITLE
Documentation / Wiki Checklist

### ISSUE THREAD

**Issue by miczed** [Hack3rz-Official/annotation-web-service#167]
### Root `README.md`
- [x] how to run the code with docker-compose locally
- [x] explanation of environment variables
- [x] explanation of MongoDB
- [x] explanation of NGINX
- [x] list and short explanation of every microservice (with link to folder in repo), coverage, errors and code smells with link to sonarcloud)
- [x] list and short explanation of all helper utils (code-fetcher, load-tester)
- [x] list of all docker containers
- [x] deployment explanation
- [x] move "How it works" to wiki
- [x] mention and link to wiki (project organization)

> First, you have to provide a `README.md` file in the root of the project, as well as of every micro service you define. As for the source code, you can use a documentation generator for the language you choose, for instance *Javadoc*. Never forget to document the tests code.

> Hopefully, you have organized everything into a wiki already. If you did so, please give some indications in the instructions file (README.md).

### Microservice `README.md`
1. include coverage statistics in header
2. link to page in Wiki
3. Configuration (Environment Variables)
4. Run Service Locally
5. Run Tests (also mention dependencies for tests e.g. MongoDB)
6. Rest API documentation (with further reference to swagger)
  6.a Request (with Curl example)
  6.b Sample Body (json formatted)
  6.c Sample Response (json formatted)
7. Documentation (which standard was used) and other source code tools (e.g. Lombok)

- [x] annotate service
- [x] predict service
- [x] training service
- [x] web api
- [x] demo-frontend (only points that apply)

### Wiki
- [x] description of project and how it works (architecture + syntax highlighting flow) -> motivate all design decisions
- [x] update image of architecture (paths are wrong for annotation service and prediction service)
- [x] description of API usage for the backend (short description and reference to swagger)
- [x] project organization
  - [x] describe project organization and workflow
  - [x] show development progress in gantt chart
  - [x] show versioning of code (extract git branching graph and put some description on the model for branching)
  - [x] report on the use of pull requests
- [x] describe continuous integration flow
  - [x] describe how we planned and used testing
  - [x] describe continuous integration flow
  - [x] mention quality check steps
- [x] microservices
  - [x] use of technologies and their motivation
  

> You have then to maintain a wiki for the project. Every GitHub project has a parallel repository where you can store *Markdown* files to compose the wiki. We are expecting you to **describe your project, its architecture, and how to use it.** In particular, we want to understand the **motivation for all of your choices**.

> You can use the wiki also to **document the usage for the API** of the backend. As an alternative, you can use specific API documentation tools, such as [[Swagger](https://swagger.io/)](https://swagger.io/), in the case you decide to use REST.
