### ISSUE TITLE
US5 - Scaling

### ISSUE THREAD

**Issue by miczed** [Hack3rz-Official/annotation-web-service#52]
As a User I want no downtime when interacting with the web service so that my workflow is not
getting interrupted.

**Acceptance Criteria:**
- [x] The system guarantees that at least one instance of a prediction worker using the best model is available at all times.
- [x] The system guarantees that at least one instance of a training worker is available.

**Todos**:
- [ ] update model periodically with cron job (or async task??) 
- [ ] remove old logic that is based on files stored on disk
